### ISSUE TITLE
Name already taken

### ISSUE THREAD

**Issue by Ferruck** [ARM-software/bob-build#12]
Hi,

i just wanted to let you know that there's already a build tool called [_Bob_](https://github.com/BobBuildTool/bob). It targets mainly cross-platform building in different variants independent of source languages and the actual compilers, but nevertheless it's a build tool, as well.

Since you seem to be not that far into development, maybe you should consider renaming your tool or at least get in touch with the developers of the "other" _Bob_.

Regards

**Comment by kilroyd** [comment]
Hi Ferruck,

Thanks for the heads up.

"Bob" does seem to be a reasonably common name for build'ish things. The specific project you linked to (BobBuildTool) seems to be more directed towards building a collection of projects (which would have an existing build system), similar to portage. bob-build is focused on building a specific project as make does.

Despite this difference, I agree that there is room for confusion. We're not wedded to the name "Bob", so renaming is a possibility that we will think about. I don't expect a change to occur in the near future - it would impact a number of things for us, and we have a number of other priorities.

In the meantime I'm happy to leave this issue open until we come to a decision.

**Comment by Ferruck** [comment]
Yes, I'm pretty sure nobody's angry about the collision, I just wanted to let you know before your project takes off.

**Comment by lukokr-aarch64** [comment]
Closing this, we are on life support at this point.
